FROM httpd:2.4

COPY ./HTML /usr/local/apache2/htdocs/

#docker build . -t ausosweb:11221
#docker run -p 8080:80 ausosweb:11221

#docker build . -t ausosweb:11222
#docker run -p 8080:80 ausosweb:11222